/*
 * Copyright 2022 Yan Kun <yan_kun_1992@foxmail.com>
 *
 * This file fork from netty.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.otavia.core.util

import java.io.{ByteArrayOutputStream, IOException, PrintStream}
import java.lang

object ThrowableUtil {

    /** Gets the stack trace from a Throwable as a String.
     *
     *  @param cause
     *    the [[Throwable]] to be examined
     *  @return
     *    the stack trace as generated by [[Throwable#printStackTrace()]] method.
     */
    def stackTraceToString(cause: Throwable): String = {
        val out  = new ByteArrayOutputStream
        val pout = new PrintStream(out)
        cause.printStackTrace(pout)
        pout.flush()

        val trace = new String(out.toByteArray)
        out.close()
        trace
    }
}
